/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package org.apache.plc4x.malbec.s88.plant.panels;

import org.apache.plc4x.malbec.s88.api.S88ChangeEvent;
import org.apache.plc4x.malbec.s88.api.S88ChangeListener;
import org.apache.plc4x.malbec.s88.api.S88Element;
import org.apache.plc4x.malbec.s88.plant.impl.Plc4xPlantModel;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Multi-instance editor for S88 Plant Elements.
 */
@TopComponent.Description(
        preferredID = "EditorTopComponent",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@Messages({
    "CTL_EditorTopComponent=Editor Window",
    "HINT_EditorTopComponent=This is a Editor window"
})
public final class EditorTopComponent extends TopComponent implements S88ChangeListener {

    private S88Element element;
    private Plc4xPlantModel model;

    public EditorTopComponent() {
        initComponents();
        setName(Bundle.CTL_EditorTopComponent());
        setToolTipText(Bundle.HINT_EditorTopComponent());
    }

    public EditorTopComponent(Plc4xPlantModel model, S88Element element) {
        this();
        this.model = model;
        this.element = element;
        updateTitle();
        
        // Listen to domain changes
        if (model != null && model.getModel() != null) {
            model.getModel().addChangeListener(this);
        }
    }

    private void updateTitle() {
        if (element != null) {
            setName(element.getId() + " [" + element.getLevel().getDisplayName() + "]");
        }
    }

    @Override
    public void onS88Change(S88ChangeEvent event) {
        // If our element was renamed or updated, refresh the tab title/content
        if (event.element().equals(element) ||
            (event.type() == S88ChangeEvent.Type.RELOADED)) {
            java.awt.EventQueue.invokeLater(this::updateTitle);
        }
    }

    @Override
    public void componentClosed() {
        // Clean up listeners to avoid memory leaks
        if (model != null && model.getModel() != null) {
            model.getModel().removeChangeListener(this);
        }
    }

    public S88Element getElement() {
        return element;
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_NEVER;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }


    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
