<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!--
        Licensed to the Apache Software Foundation (ASF) under one or more
        contributor license agreements.  See the NOTICE file distributed with
        this work for additional information regarding copyright ownership.
        The ASF licenses this file to You under the Apache License, Version 2.0
        (the "License"); you may not use this file except in compliance with
        the License.  You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
    -->

    <modelVersion>4.0.0</modelVersion>

    <parent>
    <artifactId>merlot</artifactId>
    <groupId>org.apache.plc4x</groupId>
    <version>0.13.0-SNAPSHOT</version>
  </parent>

    <groupId>org.apache.plc4x.merlot.drv.s7</groupId>
    <artifactId>org.apache.plc4x.merlot.drv.s7</artifactId>
    <version>0.13.0-SNAPSHOT</version>
    <packaging>bundle</packaging>

    <name>PLC4J: Merlot :: s7 :: Support for Plc4x S7 driver</name>
    <description>org.apache.plc4x.merlot.drv.s7 OSGi blueprint bundle project.</description>

    <properties>
        <dependency.karaf.version>4.4.7</dependency.karaf.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>5.1.9</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Version>${project.version}</Bundle-Version>
                        <Export-Package>org.apache.plc4x.merlot.drv.s7*;version=${project.version}</Export-Package>
                        <Import-Package>*</Import-Package>
                        <_removeheaders>Import-Service,Export-Service</_removeheaders>                          
                    </instructions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                    <maxmem>256M</maxmem>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.servicemix.tooling</groupId>
                <artifactId>depends-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-depends-file</id>
                        <goals>
                            <goal>generate-depends-file</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <forkCount>1</forkCount>
                    <reuseForks>false</reuseForks>
                    <systemPropertyVariables>
                        <my.system.property>foo</my.system.property>
                    </systemPropertyVariables>
                </configuration>
            </plugin>    
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-failsafe-plugin</artifactId>
              <version>${maven-failsafe-plugin.version}</version>
              <configuration>
                <forkedProcessExitTimeoutInSeconds>0</forkedProcessExitTimeoutInSeconds>
              </configuration>
            </plugin>                                       
        </plugins>
 
    </build>
    
    <dependencies>
        <dependency>
            <groupId>org.apache.plc4x.merlot.api</groupId>
            <artifactId>org.apache.plc4x.merlot.api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.plc4x</groupId>
            <artifactId>plc4j-driver-s7</artifactId>
            <version>${plc4x.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.13</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.apache.plc4x.merlot.db</groupId>
            <artifactId>org.apache.plc4x.merlot.db</artifactId>
            <version>0.13.0-SNAPSHOT</version>
        </dependency>
        
<!--        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.12.2</version>
            <scope>test</scope>
            <type>jar</type>
        </dependency> -->
                
<!--        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.12.2</version>
            <scope>test</scope>
        </dependency>                      -->
        
       <!-- Provide the KarafTestSupport -->
        <dependency>
            <groupId>org.apache.karaf.itests</groupId>
            <artifactId>common</artifactId>
            <version>4.4.7</version>
            <type>jar</type>
            <scope>test</scope>
        </dependency> 
        <!-- Define the Apache Karaf version to download and use for the test -->
        <!-- We use a released version here to avoid SNAPSHOT resolution -->
        <dependency>
            <groupId>org.apache.karaf</groupId>
            <artifactId>apache-karaf</artifactId>
            <version>${dependency.karaf.version}</version>  
            <scope>test</scope>
            <type>tar.gz</type>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.karaf</groupId>
                    <artifactId>org.apache.karaf.client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>compile</scope>
            <version>4.13.2</version>
        </dependency>        
        
        <!-- Required to use shell commands in the tests -->
        <dependency>
            <groupId>org.apache.karaf.shell</groupId>
            <artifactId>org.apache.karaf.shell.core</artifactId>
            <version>${dependency.karaf.version}</version>            
            <scope>test</scope>
        </dependency>
        
        <!-- Provide the PaxExam Karaf support -->
        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-container-karaf</artifactId>
            <version>4.14.0</version>              
            <scope>test</scope>
        </dependency>
        
        <!-- Provide the PaxExam JUnit extension -->
        <dependency>
            <groupId>org.ops4j.pax.exam</groupId>
            <artifactId>pax-exam-junit4</artifactId>
            <version>4.14.0</version>              
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.apache.geronimo.specs</groupId>
            <artifactId>geronimo-atinject_1.0_spec</artifactId>
            <version>1.2</version>
            <scope>test</scope>
        </dependency>        
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.hamcrest</artifactId>
            <version>1.3_1</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.plc4x</groupId>
            <artifactId>plc4j-driver-simulated</artifactId>
            <version>${plc4x.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.13</version>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <version>3.1.6</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
            <version>4.1.119.Final</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
