/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package ui

import (
	"context"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/apache/plc4x-extras/plc4go/tools/internal/progress"
	"github.com/apache/plc4x-extras/plc4go/tools/plc4xpcapanalyzer/internal/pcapfixture"
	"github.com/apache/plc4x-extras/plc4go/tools/plc4xpcapanalyzer/internal/protocol"
)

// These tests drive the analysis with real protocol bytes, generated by the same fixture
// builder demo mode uses. Nothing here needs a capture file on disk beforehand, a network, or
// a device.

// recordingReporter records what an analysis told it, so a test can assert the reporter is
// actually driven. It is mutex-guarded because the reporter is called from whichever goroutine
// is doing the work and the race detector runs over this package.
type recordingReporter struct {
	mu           sync.Mutex
	phases       []string
	totals       []int
	advanced     int
	doneCalls    int
	lastProgress progress.Update
}

func (r *recordingReporter) Start(total int, description string) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.phases = append(r.phases, description)
	r.totals = append(r.totals, total)
}

func (r *recordingReporter) Advance(delta int) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.advanced += delta
}

func (r *recordingReporter) SetDescription(string) {}

func (r *recordingReporter) Done() {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.doneCalls++
}

func (r *recordingReporter) snapshot() recordingReporter {
	r.mu.Lock()
	defer r.mu.Unlock()
	return recordingReporter{
		phases:       append([]string(nil), r.phases...),
		totals:       append([]int(nil), r.totals...),
		advanced:     r.advanced,
		doneCalls:    r.doneCalls,
		lastProgress: r.lastProgress,
	}
}

// writeCBus writes a C-Bus capture into a temporary directory and returns the request that
// analyses it.
func writeCBus(t *testing.T, packets []pcapfixture.Packet) Request {
	t.Helper()
	path := filepath.Join(t.TempDir(), "cbus.pcap")
	require.NoError(t, pcapfixture.WriteCBus(path, packets))
	return Request{Protocol: protocol.CBus, PcapFile: path, Client: pcapfixture.ClientIP}
}

func TestAnalyzeProducesARecordPerPacket(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())

	result := Analyze(t.Context(), request, Sink{})

	require.NoError(t, result.Err)
	assert.Len(t, result.Records, len(pcapfixture.CBusSession()),
		"every packet in the capture has to reach the table, whatever the codec made of it")
	assert.Equal(t, len(pcapfixture.CBusSession()), result.Counters.Walked)
	for i, record := range result.Records {
		assert.Positive(t, record.Number, "record %d must carry the packet number a user can compare with Wireshark", i)
		assert.Equal(t, protocol.CBus.Name, record.Protocol)
		assert.NotEmpty(t, record.Original, "record %d must keep the captured payload for the detail pane", i)
	}
}

// TestAnalyzeRoundTripsTheCleanSession is the property that makes the fixtures worth having:
// the analyzer's whole job is parse, re-serialize, compare, and a session built from real
// protocol bytes has to come back byte-identical.
func TestAnalyzeRoundTripsTheCleanSession(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())

	result := Analyze(t.Context(), request, Sink{})

	require.NoError(t, result.Err)
	assert.Zero(t, result.Counters.ParseFail)
	assert.Zero(t, result.Counters.SerializeFail)
	assert.Zero(t, result.Counters.CompareFail)
	assert.Zero(t, result.Counters.Issues(), "a clean session must produce no findings")
	for _, record := range result.Records {
		if record.Verdict == VerdictOK {
			assert.Equal(t, -1, record.DiffOffset, "packet %d compared equal, so it has no difference offset", record.Number)
			assert.Equal(t, record.Original, record.Reserialized)
		}
	}
}

// TestAnalyzeReportsTheBrokenPayloads is the other half: the deliberately broken payloads have
// to be counted as findings rather than quietly skipped.
func TestAnalyzeReportsTheBrokenPayloads(t *testing.T) {
	pinGlobals(t)
	clean := Analyze(t.Context(), writeCBus(t, pcapfixture.CBusSession()), Sink{})
	broken := Analyze(t.Context(), writeCBus(t, pcapfixture.CBusSessionWithFailures()), Sink{})

	require.NoError(t, clean.Err)
	require.NoError(t, broken.Err)
	assert.Positive(t, broken.Counters.Issues(),
		"the failure fixture exists so that the findings tab and the failure counters have something in them")
	assert.Greater(t, broken.Counters.Issues(), clean.Counters.Issues())

	var findings []Record
	for _, record := range broken.Records {
		if record.Verdict.IsIssue() {
			findings = append(findings, record)
		}
	}
	require.NotEmpty(t, findings)
	for _, finding := range findings {
		assert.NotEmpty(t, finding.Reason, "a finding with no reason tells the user nothing")
	}
}

func TestAnalyzeHandlesBacnet(t *testing.T) {
	pinGlobals(t)
	path := filepath.Join(t.TempDir(), "bacnet.pcap")
	session := pcapfixture.BacnetSession()
	require.NoError(t, pcapfixture.WriteBacnet(path, session))

	result := Analyze(t.Context(), Request{Protocol: protocol.BacnetIP, PcapFile: path, NoFilter: true}, Sink{})

	require.NoError(t, result.Err)
	assert.Len(t, result.Records, len(session))
	assert.Zero(t, result.Counters.Issues(), "the BACnet fixture round-trips, so it must produce no findings")
}

// TestAnalyzeDrivesEveryPhase pins the breadcrumb the run panel draws. Deleting a phase would
// leave the panel showing a stage the run never reaches.
func TestAnalyzeDrivesEveryPhase(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())
	reporter := &recordingReporter{}

	result := Analyze(t.Context(), request, Sink{Progress: reporter})
	require.NoError(t, result.Err)

	recorded := reporter.snapshot()
	assert.Equal(t, Phases, recorded.phases, "the run panel's breadcrumb is these phases, in this order")
	assert.Positive(t, recorded.advanced, "a bar that never advances is a bar that says nothing")
	assert.Positive(t, recorded.doneCalls, "the reporter must be finished, not abandoned")
	require.Len(t, recorded.totals, len(Phases))
	assert.Equal(t, len(pcapfixture.CBusSession()), recorded.totals[len(recorded.totals)-1],
		"the analyze phase must announce how many packets it is about to walk")
}

// TestAnalyzeObservesEveryRecord pins the streaming that fills the table while a run is in
// flight. Without it the table would stay empty until the very end of a long capture.
func TestAnalyzeObservesEveryRecord(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())

	var mu sync.Mutex
	var observed []Record
	result := Analyze(t.Context(), request, Sink{Observe: func(record Record) {
		mu.Lock()
		defer mu.Unlock()
		observed = append(observed, record)
	}})

	require.NoError(t, result.Err)
	mu.Lock()
	defer mu.Unlock()
	assert.Equal(t, result.Records, observed, "what was streamed must be exactly what was returned, in order")
}

// TestAnalyzeStopsWhenTheContextIsCancelled is what makes the esc-abort binding real.
func TestAnalyzeStopsWhenTheContextIsCancelled(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSessionWithFailures())

	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	result := Analyze(ctx, request, Sink{})

	assert.True(t, result.Aborted, "a cancelled run must say it was cancelled rather than look complete")
	assert.NoError(t, result.Err, "an abort is not a failure")
}

// TestAnalyzePacketLimitZeroMeansUnlimited is the fix for a measured defect: the analyzer reads
// a limit of zero as "stop before the first packet", and the ui subcommand never parses the
// analyze flags that would set it to MaxUint, so the old UI's analyze command reported success
// having walked nothing.
func TestAnalyzePacketLimitZeroMeansUnlimited(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())
	request.PacketLimit = 0

	result := Analyze(t.Context(), request, Sink{})

	require.NoError(t, result.Err)
	assert.Len(t, result.Records, len(pcapfixture.CBusSession()))
}

func TestAnalyzePacketLimitCutsTheRunShort(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())
	request.PacketLimit = 3

	result := Analyze(t.Context(), request, Sink{})

	require.NoError(t, result.Err)
	assert.Len(t, result.Records, 3)
}

func TestAnalyzeOnlyParseSkipsTheComparison(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())
	request.OnlyParse = true

	result := Analyze(t.Context(), request, Sink{})

	require.NoError(t, result.Err)
	for _, record := range result.Records {
		assert.Nil(t, record.Reserialized, "packet %d was only parsed, so nothing was written back", record.Number)
	}
}

func TestAnalyzeReportsAMissingCapture(t *testing.T) {
	pinGlobals(t)
	result := Analyze(t.Context(), Request{
		Protocol: protocol.CBus,
		PcapFile: filepath.Join(t.TempDir(), "absent.pcap"),
	}, Sink{})

	require.Error(t, result.Err)
	assert.Contains(t, result.Err.Error(), "absent.pcap")
	assert.Empty(t, result.Records)
}

func TestAnalyzeMeasuresElapsedWithTheInjectedClock(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())

	var calls int
	result := Analyze(t.Context(), request, Sink{Clock: func() time.Time {
		calls++
		return time.Unix(0, 0).Add(time.Duration(calls) * time.Second)
	}})

	require.NoError(t, result.Err)
	assert.Equal(t, time.Second, result.Elapsed, "elapsed must come from the injected clock, not the wall clock")
}

func TestRequestLabelIsTheCommandThatWouldReproduceIt(t *testing.T) {
	request := Request{Protocol: protocol.CBus, PcapFile: "/tmp/captures/plant.pcap"}
	assert.Equal(t, "analyze c-bus plant.pcap", request.Label())
}

func TestFirstDifference(t *testing.T) {
	for name, testCase := range map[string]struct {
		a, b []byte
		want int
	}{
		"identical":         {[]byte("abc"), []byte("abc"), -1},
		"both empty":        {nil, nil, -1},
		"differs at start":  {[]byte("abc"), []byte("xbc"), 0},
		"differs in middle": {[]byte("abcd"), []byte("abxd"), 2},
		"a is a prefix":     {[]byte("ab"), []byte("abc"), 2},
		"b is a prefix":     {[]byte("abc"), []byte("ab"), 2},
		"one empty":         {[]byte{}, []byte("a"), 0},
	} {
		t.Run(name, func(t *testing.T) {
			assert.Equal(t, testCase.want, FirstDifference(testCase.a, testCase.b))
		})
	}
}

func TestDifferingBytesCountsTheTailOfTheLongerSlice(t *testing.T) {
	assert.Equal(t, 0, differingBytes([]byte("abc"), []byte("abc")))
	assert.Equal(t, 1, differingBytes([]byte("abc"), []byte("abx")))
	assert.Equal(t, 2, differingBytes([]byte("abc"), []byte("a")))
	assert.Equal(t, 3, differingBytes([]byte("abc"), []byte("xyz")))
}

// TestHexRowCaretColumnPointsAtTheRightByte is what makes the detail pane's marker truthful.
func TestHexRowCaretColumnPointsAtTheRightByte(t *testing.T) {
	data := []byte{0x5c, 0x33, 0x31, 0x33, 0x38, 0x30, 0x30, 0x30}
	row := hexRow(data, 0, len(data), 8)

	for offset := range len(data) {
		column := hexRowCaretColumn(offset, 8)
		assert.Equal(t, hexOf(data[offset]), row[column:column+2],
			"the caret for offset %d must land on that byte's two hex digits", offset)
	}
}

// hexOf renders one byte as its two lowercase hex digits.
func hexOf(b byte) string {
	const digits = "0123456789abcdef"
	return string([]byte{digits[b>>4], digits[b&0xf]})
}

func TestHexDumpLinesRendersOffsetsAndPrintables(t *testing.T) {
	lines := HexDumpLines([]byte("hello world"), 8, 10)
	require.Len(t, lines, 2)
	assert.True(t, strings.HasPrefix(lines[0], "00000000  "), "got %q", lines[0])
	assert.Contains(t, lines[0], "|hello wo|")
	assert.True(t, strings.HasPrefix(lines[1], "00000008  "), "got %q", lines[1])
	assert.Contains(t, lines[1], "|rld|")
}

func TestHexDumpLinesSaysWhenThereIsNothing(t *testing.T) {
	assert.Equal(t, []string{"(empty)"}, HexDumpLines(nil, 8, 4))
}

func TestPreviewQuotesAndTruncates(t *testing.T) {
	assert.Equal(t, `""`, Preview(nil, 20, "."))
	assert.Equal(t, `"~~~\r"`, Preview([]byte("~~~\r"), 20, "."))
	assert.Equal(t, `"abcd.`, Preview([]byte("abcdefghij"), 6, "."))
}

func TestMessageNameStripsThePointerAndTheGeneratedPrefix(t *testing.T) {
	pinGlobals(t)
	result := Analyze(t.Context(), writeCBus(t, pcapfixture.CBusSession()), Sink{})
	require.NoError(t, result.Err)

	var named int
	for _, record := range result.Records {
		if record.Summary == "" {
			continue
		}
		named++
		assert.NotContains(t, record.Summary, "*", "%q must not carry the pointer marker", record.Summary)
		assert.NotContains(t, record.Summary, ".", "%q must be the bare type name", record.Summary)
		assert.False(t, strings.HasPrefix(record.Summary, "_"), "%q must not carry the generated-type prefix", record.Summary)
	}
	assert.Positive(t, named, "the fixture parses, so at least one record must be named")
}

func TestDirectionFollowsTheConfiguredClient(t *testing.T) {
	pinGlobals(t)
	result := Analyze(t.Context(), writeCBus(t, pcapfixture.CBusSession()), Sink{})
	require.NoError(t, result.Err)

	var requests, responses int
	for _, record := range result.Records {
		switch record.Direction {
		case DirectionRequest:
			requests++
		case DirectionResponse:
			responses++
		}
	}
	assert.Positive(t, requests, "the fixture interleaves both directions")
	assert.Positive(t, responses)
}

func TestDirectionIsUnknownWithoutAClient(t *testing.T) {
	pinGlobals(t)
	request := writeCBus(t, pcapfixture.CBusSession())
	request.Client = ""

	result := Analyze(t.Context(), request, Sink{})

	require.NoError(t, result.Err)
	for _, record := range result.Records {
		assert.Equal(t, DirectionUnknown, record.Direction,
			"with no client configured the tool must not guess which way a packet went")
	}
}

func TestVerdictIsIssueOnlyForDefects(t *testing.T) {
	for verdict, want := range map[Verdict]bool{
		VerdictOK:            false,
		VerdictSkipped:       false,
		VerdictFiltered:      false,
		VerdictNoPayload:     false,
		VerdictBytesDiffer:   true,
		VerdictParseFail:     true,
		VerdictSerializeFail: true,
	} {
		assert.Equal(t, want, verdict.IsIssue(), "verdict %s", verdict)
	}
}
