<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.apache.plc4x</groupId>
    <artifactId>plc4x-extras-parent</artifactId>
    <version>0.13.0</version>
  </parent>

  <artifactId>plc4go-extras</artifactId>
  <packaging>pom</packaging>

  <name>PLC4Go-Extras</name>
  <description>Examples, integration modules and tools for Go.</description>

  <properties>
    <project.build.outputTimestamp>2025-08-06T16:25:04Z</project.build.outputTimestamp>
    <!-- Tell Sonar where to find the sources -->
    <sonar.sources>.</sonar.sources>
    <sonar.inclusions>**</sonar.inclusions>
    <sonar.exclusions>protocols/**/*</sonar.exclusions>

    <sonar.tests>.</sonar.tests>
    <sonar.test.inclusions>**/*_test.go</sonar.test.inclusions>
    <sonar.coverage.exclusions>**/*_test.go,spi/testutils/*,**/*_plc4xgen.go,tests/**/*,tools/**/*
    </sonar.coverage.exclusions>

    <sonar.go.exclusions>**/vendor/**,**/*_mock.go,**/mock_*.go</sonar.go.exclusions>
    <!-- TODO: add json output to sonar.go.tests.reportPaths=${project.basedir}/target/go-test-report.out-->
    <sonar.go.coverage.reportPaths>${project.basedir}/target/coverage.out</sonar.go.coverage.reportPaths>

    <maven.install.skip>true</maven.install.skip>
    <!-- The deploy-goal of the go plugin uses go install to install the result, unfortunately disabling the deploy, disables the go install. -->
    <!--maven.deploy.skip>true</maven.deploy.skip-->

    <go.cover.flag>-coverprofile=target/coverage.out</go.cover.flag>

    <go.version>1.24.2</go.version>
  </properties>

  <build>
    <sourceDirectory>tools</sourceDirectory>
    <plugins>
      <!--
        Create surefire folder for report, as this is required to exist.
      -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>generate-sources</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <mkdir dir="target${file.separator}surefire-reports" />
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.igormaznitsa</groupId>
        <artifactId>gosdk-wrapper-maven-plugin</artifactId>
        <version>1.0.5</version>
        <executions>
          <!-- Run the go code-generation -->
          <execution>
            <id>default-generate</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <args>
                <arg>generate</arg>
                <!-- We want to format every package here, so we don't get dirty commits -->
                <args>./...</args>
              </args>
            </configuration>
          </execution>

          <!-- Generate mocks-->
          <execution>
            <id>generate-mocks</id>
            <phase>process-sources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <args>
                <arg>tool</arg>
                <arg>mockery</arg>
                <arg>--log-level</arg>
                <arg>info</arg>
              </args>
            </configuration>
          </execution>

          <!-- Format the codebase correctly (this mainly has an effect on generated code) -->
          <execution>
            <id>default-fmt</id>
            <phase>process-sources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <args>
                <arg>fmt</arg>
                <!-- We want to format every package here so we don't get dirty commits -->
                <arg>./...</arg>
              </args>
            </configuration>
          </execution>

          <execution>
            <id>test</id>
            <phase>test</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <skip>${skipTests}</skip>
              <args>
                <arg>tool</arg>
                <arg>gotestsum</arg>
                <arg>--junitfile</arg>
                <arg>target/surefire-reports/go-junit-report.xml</arg>
                <arg>--</arg>
                <arg>${go.cover.flag}</arg>
                <arg>./...</arg>
              </args>
            </configuration>
          </execution>

          <!-- Format (group) imports -->
          <execution>
            <id>fix-imports-internal</id>
            <phase>process-sources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <args>
                <arg>tool</arg>
                <arg>goimports-reviser</arg>
                <arg>-excludes</arg>
                <arg>.idea,.git</arg>
                <arg>./...</arg>
              </args>
            </configuration>
          </execution>

          <execution>
            <id>run-go-vet</id>
            <phase>verify</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <args>
                <arg>vet</arg>
              </args>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <goVersion>${go.version}</goVersion>
          <workDir>${project.basedir}</workDir>
        </configuration>
      </plugin>

      <!-- disabled plugins as of documentation -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <executions>
          <execution>
            <id>default-clean</id>
            <phase>none</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <id>default-jar</id>
            <phase>none</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <executions>
          <execution>
            <id>default-test</id>
            <phase>none</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <executions>
          <execution>
            <id>default-compile</id>
            <phase>none</phase>
          </execution>
          <execution>
            <id>default-testCompile</id>
            <phase>none</phase>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <executions>
          <execution>
            <id>default-install</id>
            <phase>none</phase>
          </execution>
        </executions>
      </plugin>

      <!-- Ensure we don't deploy anything -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>.os-windows-x86_64</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>x86_64</arch>
        </os>
      </activation>
      <properties>
        <!--
        Coverage doesn't work in windows because of a long path issue in cover.exe
        Tracked upstream issue: https://github.com/golang/go/issues/60785
        -->
        <go.cover.flag>-v</go.cover.flag>
      </properties>
    </profile>
    <profile>
      <id>.os-windows-aarch64</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>aarch64</arch>
        </os>
      </activation>
      <properties>
        <!--
        Coverage doesn't work in windows because of a long path issue in cover.exe
        Tracked upstream issue: https://github.com/golang/go/issues/60785
        -->
        <go.cover.flag>-v</go.cover.flag>
      </properties>
    </profile>
  </profiles>
</project>